### ISSUE TITLE
report error in the arthook.log

### ISSUE THREAD

**Issue by jackywyz** [vaioco/art-hooking-vtable#1]
cannot find function: _ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_b

**Comment by vaioco** [comment]
Hi, thank you for the report.
please, try using the latest commit.

**Comment by jackywyz** [comment]
The new version  error:
make: *** No rule to make target ` art-hooking-vtable/arthook/core/jni/json_parser/json.c', needed by

**Comment by vaioco** [comment]
thanks. it is fixed now! update the repo, please

**Comment by jackywyz** [comment]
The same error in arthook.log >
 cannot find function: _ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_b
can't find: _ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_b
cannot find symbol _ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_b!!

**Comment by vaioco** [comment]
HI @jackywyz, please can you post the full contents of arthook.log ? 
please, report also the android version you are testing on.
thanks

**Comment by jackywyz** [comment]
OK, android version 4.4.2
arthook.log contents  :

ARTDroid /art-hooking-vtable/examples/arthook_demo/jni/arthook_demo.c started
art_hand = 0x63f22128 
JNI_GetCreatedJavaVMs = 0x64740429
_ZN3art6Thread14CurrentFromGdbEv = 0x647eaa35
_ZN3art3Dbg9SuspendVMEv = 0x646bed15
_ZN3art3Dbg8ResumeVMEv = 0x646be465
_ZN3art3Dbg11SuspendSelfEv = 0x646bed31
_ZN3art10ThreadList9ResumeAllEv = 0x647f580d
_ZN3art7Runtime9instance_E = 0x64862d50
_ZN3art11ClassLinker14DumpAllClassesEi = 0x646aef65
cannot find function: _ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_b
can't find: _ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_b
cannot find symbol _ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_b!!

**Comment by vaioco** [comment]
thanks, please try the latest commit. 
it should fix the issue, in android <5.0 the symbol's name is changed.
let me know.

**Comment by jackywyz** [comment]
The test apk process crash when i hook the apk process

and the arthook.log contents:

art_hand = 0x618f5004 
JNI_GetCreatedJavaVMs = 0x61de5429
_ZN3art6Thread14CurrentFromGdbEv = 0x61e8fa35
_ZN3art3Dbg9SuspendVMEv = 0x61d63d15
_ZN3art3Dbg8ResumeVMEv = 0x61d63465
_ZN3art3Dbg11SuspendSelfEv = 0x61d63d31
_ZN3art10ThreadList9ResumeAllEv = 0x61e9a80d
_ZN3art7Runtime9instance_E = 0x61f07d50
_ZN3art11ClassLinker14DumpAllClassesEi = 0x61d53f65
arthook_entrypoint_start called 
get_jnienv called!!
dentro getcreatedjavavms 
chiamo: 0x61de5429 
 res = 0

**Comment by vaioco** [comment]
hi @jackywyz ,
did you disabled selinux (permissive mode) ?
please check in logcat for crash info (add logcat '*:E')

thanks

**Comment by jackywyz** [comment]
OK,i  set that :#  setenforce 0 

and the logcat here:

F/libc    ( 7204): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 7204 (stingmalwareapp)
F/libc    ( 7204): Unable to open connection to debuggerd: Connection refused
E/InputDispatcher(  694): channel '4225a9e8 org.sid.testingmalwareapp/org.sid.testingmalwareapp.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/Zygote  ( 7256): Zygote:  error closing descriptor
E/Zygote  ( 7256): libcore.io.ErrnoException: close failed: EBADF (Bad file number)
E/Zygote  ( 7256): 	at libcore.io.Posix.close(Native Method)
E/Zygote  ( 7256): 	at libcore.io.BlockGuardOs.close(BlockGuardOs.java:75)
E/Zygote  ( 7256): 	at com.android.internal.os.ZygoteInit.closeServerSocket(ZygoteInit.java:220)
E/Zygote  ( 7256): 	at com.android.internal.os.ZygoteConnection.handleChildProc(ZygoteConnection.java:879)
E/Zygote  ( 7256): 	at com.android.internal.os.ZygoteConnection.runOnce(ZygoteConnection.java:242)
E/Zygote  ( 7256): 	at com.android.internal.os.ZygoteInit.runSelectLoop(ZygoteInit.java:701)
E/Zygote  ( 7256): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:637)
E/Zygote  ( 7256): 	at dalvik.system.NativeStart.main(Native Method)
E/TelephonyProvider(  859): iTelephony is null!!!
E/TelephonyProvider(  859): iTelephony is null!!!

**Comment by vaioco** [comment]
ok, time to open a new issue :)
please, add more info about the error:
1) arthook.log
2) adb logcat -s ARTvtablehook
3) adb logcat | grep DEBUG 

the second is the output from the Java patch code and the latter is for catching segfault info.
do you add your own code or just compiling and running from repo?

thanks
