### ISSUE TITLE
The test apk process crash and the process reboot when I hook the test apk process

### ISSUE THREAD

**Issue by jackywyz** [vaioco/art-hooking-vtable#2]
I don't add  other codes , no more logs
Device: android 4.4.2  
platform:  MT6582
all logs in the following

logcat here:
F/libc    ( 3660): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 3660 (stingmalwareapp)
F/libc    ( 3660): Unable to open connection to debuggerd: Connection refused

arthook.log here:
art_hand = 0x615f4004 
JNI_GetCreatedJavaVMs = 0x614d1429
_ZN3art6Thread14CurrentFromGdbEv = 0x6157ba35
_ZN3art3Dbg9SuspendVMEv = 0x6144fd15
_ZN3art3Dbg8ResumeVMEv = 0x6144f465
_ZN3art3Dbg11SuspendSelfEv = 0x6144fd31
_ZN3art10ThreadList9ResumeAllEv = 0x6158680d
_ZN3art7Runtime9instance_E = 0x615f3d50
_ZN3art11ClassLinker14DumpAllClassesEi = 0x6143ff65
arthook_entrypoint_start called 
get_jnienv called!!
dentro getcreatedjavavms 
chiamo: 0x614d1429 
 res = 0

**Comment by vaioco** [comment]
please, what device are you using?
maybe you have useful coredumps inside the /data/tombstones/ dir...
i can't understand the problem from the logcat logs..

thanks

**Comment by jackywyz** [comment]
My phone is lenovo a3800d , with mtk cpu and 4.4.2 device   ,and  the /data/local/tmp/dex dir has been created by init.sh  file . I think i should test more phones by the hook scripts.

**Comment by vaioco** [comment]
Hi @jackywyz ,
if you could add more info about your problem maybe I can help you..
for example, the tombstone relative to your crash?

**Comment by 534954622** [comment]
I think this porplem is that add busybox for the common in demo code：
ex.  "busybox awk "    replace  "awk"
