### ISSUE TITLE
Not working on emulator64-arm android 5.1

### ISSUE THREAD

**Issue by wkt** [vaioco/art-hooking-vtable#3]
arthook.log is empty

bash startdemo.sh 
checking if checkjni is enabled...
ok, checkjni is already enabled!
moving on..
this script must be runned on device or emulator !!
ALL DONE!! Now you can inject the arthook .so into the target process using the runhijack.sh script!!

Please, remember to chown the "dex/opt" dir with the $UID of the target application!
run in this dir: chown $UID:$UID dex/opt

starting testing app
Starting: Intent { cmp=org.sid.testingmalwareapp/.MainActivity }
Status: ok
Activity: org.sid.testingmalwareapp/.MainActivity
ThisTime: 1070
TotalTime: 1070
WaitTime: 1292
Complete
target appliation pid: 5092 and 10053
starting hooking....
check dependencies
hijack su pid: 5092
mprotect: 0xb6d9e32c
dlopen: 0xb6eeef4d

pc=b6d9ec9c lr=b6d78143 sp=bea120f0 fp=14c01040
r0=fffffffc r1=bea12150
r2=10 r3=ffffffff
stack: 0xbe214000-0xbea13000 leng = 8384512
executing injection code at 0xbea120a0
calling mprotect
library injection completed!
eseguito

patch for hijack:
 
diff --git a/hijack/jni/Android.mk b/hijack/jni/Android.mk
index 5d78442..60f2944 100644
--- a/hijack/jni/Android.mk
+++ b/hijack/jni/Android.mk
@@ -20,5 +20,8 @@ LOCAL_MODULE    := hijack
 LOCAL_SRC_FILES := ../hijack.c 
 LOCAL_ARM_MODE := arm
 LOCAL_CFLAGS := -g
+LOCAL_CFLAGS += -fPIE
+LOCAL_LDFLAGS += -fPIE -pie
+
 
 include $(BUILD_EXECUTABLE)

**Comment by vaioco** [comment]
Hi @wkt, thank you for your question.
ARTDroid, so far, does not support 64 bit arch. We are adding this feature for the next release (2 weeks)
