### ISSUE TITLE
Hello ,can you tell me "0x170" represent what? which used in method "searchInMemoryVtable_all"

### ISSUE THREAD

**Issue by wonder2014** [vaioco/art-hooking-vtable#5]
Hi ,I don't know the meaning of 0x170 which used in method "searchInMemoryVtable_all" .can you tell me?

**Comment by vaioco** [comment]
Hi @wonder2014 , thank you for your question.
It is the static offset of the embedded vtable.

**Comment by wonder2014** [comment]
Hi  @vaioco,Thanks for your reply.

**Comment by vaioco** [comment]
You are welcome
