### ISSUE TITLE
hi！run the art-hooking-vtable one-script is some error！could you help me？

### ISSUE THREAD

**Issue by 534954622** [vaioco/art-hooking-vtable#6]
ARTDroid /usr1/test/ARTHook_openCode/art-hooking-vtable/examples/arthook_demo/jni/arthook_demo.c started pid = 6398 
art_hand = 0x416d8004 
JNI_GetCreatedJavaVMs = 0x415b3f4d
_ZN3art6Thread14CurrentFromGdbEv = 0x4165f4c5
_ZN3art3Dbg9SuspendVMEv = 0x41532d95
_ZN3art3Dbg8ResumeVMEv = 0x415324e9
_ZN3art3Dbg11SuspendSelfEv = 0x41532db1
_ZN3art10ThreadList9ResumeAllEv = 0x4166a34d
_ZN3art7Runtime9instance_E = 0x416d7d50
_ZN3art11ClassLinker14DumpAllClassesEi = 0x41522e61
processIsZygote running command: ps | grep zygote | busybox tr -s " " | busybox cut -d " " -f 2 
_runCommand buffer = 5103
 
_runCommand AAAA ritorno 5103

arthook_entrypoint_start called 
get_jnienv called!!
dentro getcreatedjavavms 
chiamo: 0x415b3f4d 
 res = 0
called getcreatedjavavms, results: 0x416d3a90 , count = 1 
jnienv = 0x41f0ed30 
config_init called with : /data/local/tmp/test.json len 25 
**ERROR stat on /data/local/tmp/test.json
ERROR in json parser!!**
getAPIVersion CALLED!!!
API version: 19 

there are some error in json？！！！！！

I  am  run this demo in nexus 5， Android 4.4.2

**Comment by vaioco** [comment]
Hi @534954622,
thanks for your interest on ARTDroid. please, could you check if that file exists?

**Comment by 534954622** [comment]
Hi @vaioco 
thanks for you reply！  I Create json file ，and ARTDroid can work !
are you doing the jobs that ARTDroid for ARM x64 ?

**Comment by vaioco** [comment]
Hi @534954622 ,
please we are moving to https://github.com/vaioco/ARTDroid
