### ISSUE TITLE
arthook on android 6.0

### ISSUE THREAD

**Issue by ecrasy** [vaioco/art-hooking-vtable#7]
Trying to hook android 6.0 with symbol
_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_j

hook function return success, but hook invoke method not get called

thanks for all the things
may you the best everyday

**Comment by vaioco** [comment]
HI @ecrasy ,
please use https://github.com/vaioco/ARTDroid. thanks
